# ==================================================
# WordPress v2.0 - 添加健康检查
# 学习目标：理解 Liveness 和 Readiness Probes
# ==================================================
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-v2
  labels:
    version: "2.0"
---
# MySQL Secret（与 v1.0 相同）
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-v2
type: Opaque
data:
  # root 密码: MyR00tP@ss (Base64)
  mysql-root-password: TXlSMDB0UEBzcw==
  # WordPress 数据库密码: WPP@ssw0rd (Base64)
  mysql-password: V1BQQHNzdzByZA==
---
# MySQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: wordpress-v2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress-v2
spec:
  replicas: 1  # v2.0 暂时单实例
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wpuser
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          # ===== 新增：MySQL 健康检查 =====
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30  # 启动后 30 秒开始检查
            periodSeconds: 10        # 每 10 秒检查一次
            timeoutSeconds: 5        # 5 秒超时
            failureThreshold: 3      # 连续失败 3 次才重启
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 10  # 启动后 10 秒开始检查
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wordpress-v2
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Headless Service
---
# WordPress PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress-v2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
# WordPress Deployment（重点：健康检查）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-v2
spec:
  replicas: 1  # 阶段 1 先用单副本
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.2-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql:3306
            - name: WORDPRESS_DB_USER
              value: wpuser
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
          # ===== 新增：WordPress 健康检查 =====
          livenessProbe:
            httpGet:
              path: /wp-admin/install.php  # 检查 WordPress 安装页面
              port: 80
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 60   # WordPress 启动较慢，60 秒后检查
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /wp-login.php      # 检查登录页面（更轻量）
              port: 80
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 30   # 30 秒后检查就绪
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1       # 成功 1 次即标记就绪
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
---
# WordPress Service（NodePort 保持，后续阶段改 ClusterIP）
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-v2
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # 与 v1.0 区分，使用 30081